/**
 * Vercel Build Script
 * Generates env-config.js with production environment variables
 * Run: node scripts/build.js
 *
 * On Vercel, set these environment variables:
 *   API_BASE_URL  = https://your-railway-app.up.railway.app/api
 *   PINATA_API_KEY = your-pinata-api-key
 *   PINATA_SECRET_KEY = your-pinata-secret-key
 *   IPFS_GATEWAY = https://gateway.pinata.cloud/ipfs/
 */

const fs = require('fs');
const path = require('path');

const frontendDir = path.resolve(__dirname, '../frontend');

// Read env vars (set on Vercel dashboard)
const apiBaseUrl = process.env.API_BASE_URL || 'http://localhost:3000/api';
const pinataApiKey = process.env.PINATA_API_KEY || '';
const pinataSecretKey = process.env.PINATA_SECRET_KEY || '';
const ipfsGateway = process.env.IPFS_GATEWAY || 'https://gateway.pinata.cloud/ipfs/';

// Generate env-config.js
const envConfigContent = `// Auto-generated by build.js — DO NOT EDIT MANUALLY
// Generated at: ${new Date().toISOString()}
window.APP_CONFIG = {
    API_BASE_URL: '${apiBaseUrl}',
    PINATA_API_KEY: '${pinataApiKey}',
    PINATA_SECRET_KEY: '${pinataSecretKey}',
    IPFS_GATEWAY: '${ipfsGateway}'
};
`;

const envConfigPath = path.join(frontendDir, 'env-config.js');
fs.writeFileSync(envConfigPath, envConfigContent);
console.log(`✅ Generated env-config.js with API_BASE_URL: ${apiBaseUrl}`);

// Ensure env-config.js is the first script in every HTML file
const htmlFiles = fs.readdirSync(frontendDir).filter(f => f.endsWith('.html'));
let updated = 0;

for (const file of htmlFiles) {
    const filePath = path.join(frontendDir, file);
    let content = fs.readFileSync(filePath, 'utf8');

    // Skip if already has env-config.js
    if (content.includes('env-config.js')) {
        continue;
    }

    // Insert env-config.js BEFORE the first <script src="config.js"> tag
    const newContent = content.replace(
        /(\s*<script src="config\.js"><\/script>)/,
        '\n  <script src="env-config.js"></script>$1'
    );

    if (newContent !== content) {
        fs.writeFileSync(filePath, newContent);
        updated++;
        console.log(`✅ Updated ${file} with env-config.js`);
    }
}

console.log(`\n🚀 Build complete! Updated ${updated} HTML files.`);
console.log(`   API URL: ${apiBaseUrl}`);
console.log(`   IPFS: ${pinataApiKey ? 'Pinata' : 'Local (no Pinata key set)'}`);
